# BOOKING STATUSES
BOOKING_STATUS_AWAITING_PAYMENT = "AWAITING_PAYMENT"
BOOKING_STATUS_PAID = "PAID"
BOOKING_STATUS_CONFIRMED = "CONFIRMED"
BOOKING_STATUS_PAYMENT_AUTHORISED = "PAYMENT_AUTHORISED"
BOOKING_STATUS_PENDING_HOST = "PENDING_HOST"
BOOKING_STATUS_FAILED_PAYMENT = "FAILED_PAYMENT"
BOOKING_STATUS_REJECTED = "REJECTED"
BOOKING_STATUS_EXPIRED = "EXPIRED"
BOOKING_STATUS_CANCELLED = "CANCELLED"

# BOOKING MODES
BOOKING_MODE_INSTANT = "INSTANT"
BOOKING_MODE_REQUEST = "REQUEST"

# DEPOSIT STATUSES
DEPOSIT_STATUS_HELD = "HELD"
DEPOSIT_STATUS_RELEASED = "RELEASED"
DEPOSIT_STATUS_CAPTURED = "CAPTURED"
DEPOSIT_STATUS_RESOLVED = "RESOLVED"

# TRANSACTION TYPES
TXN_TYPE_BOOKING_CAPTURE = "BOOKING_PAYMENT_CAPTURE"
TXN_TYPE_BOOKING_AUTHORIZE = "BOOKING_PAYMENT_AUTHORIZE"
TXN_TYPE_PAYMENT_VOID = "PAYMENT_VOID"
TXN_TYPE_DEPOSIT_PREAUTH = "DEPOSIT_PREAUTHORIZE"
TXN_TYPE_DEPOSIT_RELEASE = "DEPOSIT_RELEASE"
TXN_TYPE_DEPOSIT_CAPTURE = "DEPOSIT_CAPTURE"

# PAYMENT STATUSES
PAYMENT_STATUS_SUCCESS = "SUCCESS"
PAYMENT_STATUS_AUTHORIZED = "AUTHORIZED"
PAYMENT_STATUS_HELD = "HELD"
PAYMENT_STATUS_RELEASED = "RELEASED"
PAYMENT_STATUS_CAPTURED = "CAPTURED"
PAYMENT_STATUS_VOIDED = "VOIDED"
PAYMENT_STATUS_FAILED = "FAILED"

# INSPECTION CONDITIONS
CONDITION_GOOD = "GOOD"
CONDITION_BAD = "BAD"

# DEPOSIT ACTIONS
DEPOSIT_ACTION_RELEASE = "RELEASE"
DEPOSIT_ACTION_CAPTURE = "CAPTURE"
DEPOSIT_ACTION_AUTO_RELEASE = "AUTO_RELEASE"

# DEPOSIT REASONS
DEPOSIT_REASON_HOST_REPORT = "HOST_REPORT"
DEPOSIT_REASON_DAMAGE = "DAMAGE"
DEPOSIT_REASON_NO_REPORT = "NO_REPORT_48HR"

# RABBITMQ
RABBITMQ_EXCHANGE = "booking_events"
EVENT_BOOKING_CONFIRMED = "booking.confirmed"
EVENT_BOOKING_REQUESTED = "booking.requested"
EVENT_BOOKING_DECLINED = "booking.declined"
EVENT_BOOKING_EXPIRED = "booking.expired"
EVENT_PAYMENT_SUCCESS = "payment.success"
EVENT_PAYMENT_HELD = "payment.held"
EVENT_PAYMENT_ERROR = "payment.error"
EVENT_DEPOSIT_RESOLVED = "deposit.resolved"

# SERVICE URLS (internal Docker network names)
USERS_SERVICE_URL = "http://users-service:5003"
LISTINGS_SERVICE_URL = "http://listings-service:5004"
AVAILABILITY_SERVICE_URL = "http://availability-service:5005"
STAY_SERVICE_URL = "http://stay-service:5006"
INSPECTION_SERVICE_URL = "http://inspection-service:5007"
PAYMENT_LOGS_SERVICE_URL = "http://payment-logs-service:5008"
LISTINGS_SEARCH_SERVICE_URL = "http://listings-search-service:5009"
PAYMENT_GATEWAY_URL = "http://payment-gateway-wrapper:5010"
BOOKING_SERVICE_URL = "http://booking-service:5001"
DEPOSIT_RESOLUTION_URL = "http://deposit-resolution:5002"

# USER ROLES
ROLE_GUEST = "guest"
ROLE_HOST = "host"
